[[sensors]]
name = "cpu_fan"
type = "fan"
file = "fan_input1"
range = [1000,2200]
led = ["controller", "zone"]
#led = ["Chroma", "1"]
#led = ["contoller", "key"]


[[leds]]
name = "Logitech"
type = "Keyboard"

[[leds]]
name =  "Chroma"
zones = [7,7,7,10,11,34]